import { ArrowRight, Check, MessageCircle } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { Button } from '../components/common/Button';
import { Breadcrumbs } from '../components/common/Breadcrumbs';
import { CollectionCard } from '../components/common/CollectionCard';
import { WhatsAppCta } from '../components/common/WhatsAppCta';
import { collections, site } from '../data/site';

export default function CollectionDetail() { const { slug } = useParams(); const collection = collections.find(c => c.slug === slug); if (!collection) return <NotFoundCollection />; const related = collections.filter(c => c.slug !== slug && Boolean(c.image)).slice(0, 2); return <main><section className={`detail-hero theme-${collection.theme}`}><div className="container"><Breadcrumbs current={collection.name} /><div className="detail-grid"><div className="detail-copy"><span className="eyebrow">{collection.eyebrow}</span><h1>{collection.name}</h1><p>{collection.longDescription}</p><Button href={site.whatsappUrl(`Hi Sashwari, I would like to know about the ${collection.name}.`)}><MessageCircle size={17} /> Enquire about this range</Button></div><div className="detail-image">{collection.image ? <img src={collection.image} alt={`${collection.name} product collection`} /> : <div className="detail-image-fallback"><span>{collection.name}</span></div>}</div></div></div></section><section className="section"><div className="container detail-content"><div><span className="eyebrow">The ritual</span><h2>Designed around your skin story.</h2><p>Use this range as a starting point, then speak with Sashwari for product guidance that fits your routine and comfort level.</p><div className="benefit-list">{collection.benefits.map(b => <span key={b}><Check size={17} />{b}</span>)}</div></div><aside className="suitable-card"><span className="eyebrow">Suitable for</span><h3>{collection.suitableFor}</h3><p>Contact us for details about individual products and how to introduce them into your routine.</p></aside></div></section><section className="section section-soft"><div className="container"><span className="eyebrow">Recommended order</span><h2>Keep it simple, keep it consistent.</h2><div className="routine-line">{collection.routine.map((step, i) => <div key={step}><b>0{i + 1}</b><span>{step}</span>{i < collection.routine.length - 1 && <ArrowRight size={16} />}</div>)}</div><div className="product-list">{collection.products.map((product, i) => <div className="product-card" key={product}><span>0{i + 1}</span><div><h3>{product}</h3><p>Contact for product details, availability and guidance.</p></div><a href={site.whatsappUrl(`Hi Sashwari, please share details about ${product}.`)} aria-label={`Ask about ${product}`}><MessageCircle size={18} /></a></div>)}</div><p className="usage-note"><b>Usage note:</b> Introduce products thoughtfully and follow the guidance provided with your purchase. If you have a persistent skin concern, seek advice from a qualified healthcare professional.</p></div></section><section className="section"><div className="container"><div className="section-heading"><div><span className="eyebrow">Keep exploring</span><h2>More from Sashwari.</h2></div></div><div className="collection-grid related-grid">{related.map(c => <CollectionCard collection={c} key={c.slug} />)}</div><WhatsAppCta compact /></div></section></main>; }
function NotFoundCollection() { return <section className="section"><div className="container empty-state"><span className="eyebrow">Collection unavailable</span><h1>We couldn’t find that range.</h1><Link className="text-link" to="/collections">Back to collections <ArrowRight size={16} /></Link></div></section>; }
