const { chromium } = require('/private/tmp/sashwari-qa/node_modules/playwright');
const fs=require('fs'); const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:1440,height:950}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>sessionStorage.setItem('sashwari-loaded','true'));
 await page.goto('http://127.0.0.1:5173/collections', {waitUntil:'domcontentloaded'});await page.locator('.brand-loader').waitFor({state:'visible'});await page.locator('.brand-loader').waitFor({state:'detached'});await page.reload({waitUntil:'domcontentloaded'});await page.locator('.brand-loader').waitFor({state:'visible'});await page.locator('.brand-loader').waitFor({state:'detached'});
 await page.getByPlaceholder('Search collections').fill('pimple');assert.equal(await page.locator('.collection-card').count(),1);await page.getByPlaceholder('Search collections').fill('');await page.getByRole('button',{name:'Comfort',exact:true}).click();assert.equal(await page.locator('.collection-card').count(),1);await page.getByRole('button',{name:'All ranges',exact:true}).click();
 await page.locator('.collection-card').first().hover();await page.waitForTimeout(600);assert.notEqual(await page.locator('.collection-card').first().evaluate(e=>getComputedStyle(e).transform),'none');
 await page.locator('.nav-links').getByRole('link',{name:'Our science'}).click();await page.waitForTimeout(120);assert.equal(await page.locator('.route-sweep').count(),0);await page.waitForTimeout(1600);assert.match(await page.locator('h1').innerText(),/Thoughtful care/);assert.equal(await page.evaluate(()=>scrollY),0);assert.equal(await page.locator('.brand-loader').count(),0);
 await page.locator('.page-hero-media').hover({position:{x:100,y:100}});await page.waitForTimeout(600);assert.notEqual(await page.locator('.hero-media-drift').evaluate(e=>getComputedStyle(e).transform),'none');
 await page.locator('.nav-links').getByRole('link',{name:'Home',exact:true}).click();await page.waitForTimeout(1600);const carousel=page.locator('.video-carousel');await carousel.getByRole('button',{name:'Next slide'}).click();await page.waitForTimeout(800);assert.match(await carousel.locator('.carousel-count').innerText(),/02/);await carousel.press('ArrowRight');await page.waitForTimeout(800);assert.match(await carousel.locator('.carousel-count').innerText(),/03/);await carousel.getByRole('button',{name:'Pause carousel'}).click();assert.equal(await carousel.getByRole('button',{name:'Play carousel'}).count(),1);
 await page.setViewportSize({width:375,height:850});await page.getByRole('button',{name:'Open menu',exact:true}).click();await page.locator('.nav-links').getByRole('link',{name:'Contact',exact:true}).click();await page.waitForTimeout(1500);assert.equal(await page.locator('.nav-links.open').count(),0);assert.equal(await page.locator('body.menu-open').count(),0);
 await page.locator('input[name=name]').fill('Test visitor');await page.locator('input[name=phone]').fill('0770000000');await page.getByRole('button',{name:'Open WhatsApp enquiry'}).click();await page.waitForTimeout(200);assert.match(await page.getByRole('alert').innerText(),/consent/);
 // Intercept the external navigation: verify message preparation without contacting anyone.
 let prepared='';await page.route('https://wa.me/**',r=>{prepared=r.request().url();return r.abort();});await page.locator('input[name=consent]').check();await page.getByRole('button',{name:'Open WhatsApp enquiry'}).click();await page.waitForTimeout(500);assert.match(decodeURIComponent(prepared),/Test visitor/);
 await page.emulateMedia({reducedMotion:'reduce'});await page.goto('http://127.0.0.1:5173/our-science');await page.waitForTimeout(500);assert.equal(await page.locator('.route-sweep').count(),0);assert.equal(await page.locator('h1').evaluate(e=>getComputedStyle(e).opacity),'1');assert.equal(await page.locator('.hero-orbit').evaluate(e=>getComputedStyle(e).display),'none');
 await page.goto('http://127.0.0.1:5173/');await page.waitForTimeout(500);const before=await page.locator('.video-carousel .carousel-count').innerText();await page.waitForTimeout(6500);assert.equal(await page.locator('.video-carousel .carousel-count').innerText(),before);assert.equal(await page.locator('video').evaluate(v=>v.paused),true);
 // Swipe works with reduced motion, without autoplay.
 await page.locator('.video-carousel').evaluate(el => { const start = new Event('touchstart', {bubbles:true}); start.touches=[{clientX:300}]; el.dispatchEvent(start); const end=new Event('touchend',{bubbles:true}); end.changedTouches=[{clientX:100}]; el.dispatchEvent(end); });await page.waitForTimeout(250);assert.match(await page.locator('.video-carousel .carousel-count').innerText(),/02/);
 assert.deepEqual(errors,[]);fs.writeFileSync('qa/interactions.json',JSON.stringify({passed:true,checks:['search','filters','card hover','smooth route transition without logo sweep','scroll reset','first-load loader separation','hero pointer motion','carousel next','carousel keyboard','carousel pause','mobile menu','form consent','intercepted WhatsApp message','reduced motion','reduced-motion video pause','touch swipe'],errors},null,2));console.log('All interaction checks passed');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
