import { useEffect, useRef, useState } from 'react';
import { AnimatePresence, motion, useReducedMotion } from 'motion/react';
import { ChevronLeft, ChevronRight, Pause, Play } from 'lucide-react';
import { ease } from './motion';

export function MediaCarousel({ sources, video = false, className = '', label }) {
 const reduced = useReducedMotion(); const [index, setIndex] = useState(0); const [paused, setPaused] = useState(false); const [hover, setHover] = useState(false); const [visible, setVisible] = useState(true); const [hidden, setHidden] = useState(document.hidden);
 const root = useRef(null); const media = useRef(null); const start = useRef(null);
 const playing = !paused && !hover && visible && !hidden && !reduced;
 const go = amount => setIndex(i => (i + amount + sources.length) % sources.length);
 useEffect(() => { const observer = new IntersectionObserver(([entry]) => setVisible(entry.isIntersecting)); observer.observe(root.current); const visibility = () => setHidden(document.hidden); document.addEventListener('visibilitychange', visibility); return () => { observer.disconnect(); document.removeEventListener('visibilitychange', visibility); }; }, []);
 useEffect(() => { if (!playing) return; const timer = setInterval(() => go(1), 6200); return () => clearInterval(timer); }, [playing, index]);
 useEffect(() => { if (!video || !media.current) return; if (playing) media.current.play().catch(() => {}); else media.current.pause(); }, [playing, index, video]);
 const variants = { initial: { x: reduced ? 0 : '100%', scale: reduced ? 1 : 1.08 }, animate: { x: 0, scale: 1 }, exit: { x: reduced ? 0 : '-100%' } };
 return <div ref={root} className={`media-carousel ${className}`} role="region" aria-roledescription="carousel" aria-label={label} tabIndex={0} onMouseEnter={() => setHover(true)} onMouseLeave={() => setHover(false)} onFocus={() => setHover(true)} onBlur={e => { if (!e.currentTarget.contains(e.relatedTarget)) setHover(false); }} onKeyDown={e => { if (e.key === 'ArrowLeft' || e.key === 'ArrowRight') { e.preventDefault(); go(e.key === 'ArrowLeft' ? -1 : 1); } }} onTouchStart={e => { start.current = e.touches[0].clientX; }} onTouchEnd={e => { if (start.current !== null) { const delta = e.changedTouches[0].clientX - start.current; if (Math.abs(delta) > 45) go(delta > 0 ? -1 : 1); } start.current = null; }}>
 <div className="carousel-viewport"><AnimatePresence initial={false}>{video ? <motion.video key={index} ref={media} className="hero-video" src={sources[index]} muted playsInline loop preload="metadata" aria-label={`Skincare ritual film ${index + 1}`} variants={variants} initial="initial" animate="animate" exit="exit" transition={{ x: { duration: reduced ? .1 : .7, ease }, scale: { duration: reduced ? .1 : 5.8, ease } }} /> : <motion.img key={index} src={sources[index]} alt={`Sashwari skincare editorial ${index + 1}`} loading="lazy" variants={variants} initial="initial" animate="animate" exit="exit" transition={{ x: { duration: reduced ? .1 : .7, ease }, scale: { duration: reduced ? .1 : 5.8, ease } }} />}</AnimatePresence></div>
 <div className="carousel-controls"><button type="button" onClick={() => go(-1)} aria-label="Previous slide"><ChevronLeft size={18} /></button><span className="carousel-count" aria-live={playing ? 'off' : 'polite'}>{String(index + 1).padStart(2, '0')} / {String(sources.length).padStart(2, '0')}</span><div className="carousel-progress" key={`${index}-${playing}`}><span style={{ animationPlayState: playing ? 'running' : 'paused' }} /></div><button type="button" onClick={() => setPaused(p => !p)} aria-label={paused || reduced ? 'Play carousel' : 'Pause carousel'} disabled={reduced}>{paused || reduced ? <Play size={16} /> : <Pause size={16} />}</button><button type="button" onClick={() => go(1)} aria-label="Next slide"><ChevronRight size={18} /></button></div></div>;
}
